name: Backend Python CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar el código del repositorio
    - name: Checkout de código
      uses: actions/checkout@v4

    # 2. Configurar el entorno de Python
    - name: Configurar Python 3.11
      uses: actions/setup-python@v5
      with:
        python-node: '3.11'
        cache: 'pip' # Cachea las librerías para que corra más rápido

    # 3. Instalar dependencias en el entorno virtual del contenedor de GitHub
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # 4. Prueba de humo: Verificar que Uvicorn puede cargar la app sin romper por Imports
    - name: Validar importaciones de la App (Prueba de humo)
      run: |
        python -c "from app.main import app; print('¡Estructura e importaciones correctas!')"